version: "3.8"

services:

  neo4j:
    container_name: "neo4j_service"
    image: neo4j:latest
    restart: always
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/password
    volumes:
      - hayat_neo4j:/data
volumes:
  hayat_neo4j:
